name: Build and Deploy to GitHub Pages

on:
  # 当你向 main 分支推送代码时触发
  push:
    branches:
      - main  # 或者你的主分支名，可能是 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 第一步：拉取你的仓库代码
      - name: Checkout
        uses: actions/checkout@v3

      # 第二步：生成版本号并替换HTML文件中的占位符
      - name: Generate Version and Replace Placeholder
        run: |
          # 获取最新一次提交的日期，格式为 YYYYMMDD
          VERSION_DATE=$(git log -1 --format=%cd --date=format:%Y%m%d)
          echo "Latest Commit Date: $VERSION_DATE"
          
          # 在 index.html 文件中查找占位符 __VERSION__ 并替换为实际版本号
          # 注意：如果你的主文件名不是 index.html，请修改下面的文件名
          sed -i "s/__VERSION__/v$VERSION_DATE/g" index.html

      # 第三步：部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 部署的目录，'.' 表示整个仓库根目录
          publish_dir: .
